### ISSUE TITLE
Could not build module 'TencentOpenApi'

### ISSUE THREAD

**Issue by gityoung** [Dwarven/TencentOpenAPI-Mirror#1]
Could not build module 'TencentOpenApi'

**Comment by Dwarven** [comment]
pod cache clean TencentOpenAPI-Mirror --all
rm -rf Path/To/YourProject/Pods/TencentOpenAPI-Mirror
pod install

**Comment by mr-huangjian** [comment]
可以参考下我的解决办法：https://juejin.cn/post/6916432417506983949/
